// <auto-generated />
namespace Test.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class added_tipi_contatto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_tipi_contatto));
        
        string IMigrationMetadata.Id
        {
            get { return "202003021559215_added_tipi_contatto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
